### ISSUE TITLE
Show handles for nodes

### ISSUE THREAD

**Issue by thundernixon** [RafalBuchner/mirroringPane#1]
In the mirrored image, it's awesome that I can see fill, stroke, and/or nodes.

However, it is surprising to see off-curve nodes without handles/lines connecting them to their on-curve node parents. Without these, it can be unclear what on-curve node each is attached to, so it would be handy to have them showing, as well.

![image](https://user-images.githubusercontent.com/7355414/60195170-9d6f7b00-9808-11e9-9a31-c7d5ad70f7f2.png)

**Comment by RafalBuchner** [comment]
done
