### ISSUE TITLE
Unchecking "show mirrored glyph" doesn't always make mirror go away

### ISSUE THREAD

**Issue by thundernixon** [RafalBuchner/mirroringPane#4]
Unchecking "show mirrored glyph" doesn't always make mirror go away. 

It seems to work if I switch to another app (e.g. Chrome), then back to RoboFont.

![image](https://user-images.githubusercontent.com/7355414/60201268-db26d080-9815-11e9-91af-371fbdab4fb9.png)

**Comment by thundernixon** [comment]
UPDATE: nevermind; the mirrored glyph displays again, once I start interacting with the Glyph Window again.

**Comment by RafalBuchner** [comment]
still it should update glyph view, I will look into that
